#!/bin/sh
set -e

/usr/bin/ldid -S /usr/libexec/iosipd
/usr/bin/ldid -S /usr/bin/iosipctl
/usr/bin/ldid -S /Library/MobileSubstrate/DynamicLibraries/IOSIP.dylib
/usr/bin/ldid -S /Library/PreferenceBundles/IOSIPPrefs.bundle/IOSIPPrefs
/bin/rm -f /var/mobile/Library/IOSIP/ui-command.plist
/bin/rm -f /var/mobile/Library/IOSIP/events.plist
launchctl unload /Library/LaunchDaemons/me.ancal.iosipd.plist \
    2>/dev/null || true
launchctl load /Library/LaunchDaemons/me.ancal.iosipd.plist
killall MobilePhone 2>/dev/null || true
killall Preferences 2>/dev/null || true
killall SpringBoard 2>/dev/null || true

exit 0
