#!/bin/sh
set +e

/bin/launchctl unload /Library/LaunchDaemons/me.ancal.iosipd.plist \
    >/dev/null 2>&1 || true
/usr/bin/killall iosipd >/dev/null 2>&1 || true
/bin/rm -f /var/run/iosip.sock \
    /var/mobile/Library/IOSIP/iosip.sock
/bin/launchctl load /Library/LaunchDaemons/me.ancal.iosipd.plist \
    >/dev/null 2>&1 || true
/bin/sleep 1
if ! /usr/bin/iosipctl STATUS >/dev/null 2>&1; then
    /usr/libexec/iosipd </dev/null >/dev/null 2>&1 &
    /bin/sleep 2
fi

exit 0
